package.json, src/network/download.ts, src/network/errors/codes.ts, src/network/errors/download.ts, src/network/errors/index.ts, src/network/errors/upload.ts, src/network/types.ts, src/network/upload.ts, test/network/download.test.ts, test/network/upload.test.ts
- Network Upload/Download require a `validateMnemonic()` to force mnemonic validation
=> [_]: feat/network-validate-mnemonic

src/shared/http/client.ts
Some errors received from the API was being reported as [object Object] when converting to string, because they were objects, this PR solves those cases where the error message is an object
=> [_]: Replace toString by JSON.stringify to cover object cases

package.json, src/drive/share/index.ts, src/drive/share/types.ts
- For create now sends the plainPassword in body not in headers
=> [_]: hotfix(share-links): add plainPassword to create endpoint

package.json, src/drive/share/index.ts, src/drive/share/types.ts
* Endpoint to delete invitations has been added.
* Endpoint for updating user roles has also been updated.
=> [_]: feat/add endpoint to decline invitations

package.json, src/drive/share/index.ts, src/drive/share/types.ts
- Added notifyUser and notificationMessage fields
=> [_]: Added notifyUser and notification message fields to payload

package.json, src/drive/payments/index.ts
**PROBLEM:**
When the user try to update the subscription. Stripe requires the 3DS.
**FIX:** 
Sends the clientSecret in case the user has to authorize the payment to request the payment from the frontend
=> [_]: feat/request 3DS if needed

package.json, src/drive/payments/index.ts, src/drive/payments/types.ts
Currency param has been added for:
* Get the USD prices.
* Send the currency param when creating a checkout payment.
=> [MKT-217]: feat/add currency param to get the correct prices

package.json, src/auth/index.ts
For the auto unblock account feature, we need to distinguish between codes thrown by the backend. This is currently preventing us from knowing error codes.
=> [PB-115]: fix/throw error with code instead of only message on user login

package.json, src/drive/payments/index.ts, src/drive/payments/types.ts, test/drive/storage/index.test.ts, test/drive/storage/mothers/folderContentResponse.mother.ts
- Enable a new call to update the payment method for subscriptions.
- Update methods to receive a `subscriptionType` (`business` and `individual`)
- TEST: Storage test repair (add missing fields)
- Payments: https://github.com/internxt/payments/pull/66
- Use Case in drive-web: https://github.com/internxt/drive-web/pull/1151
=> [PB-2222, PB-2115] feat: update subscriptions payment methods

package.json, src/drive/storage/index.ts
- Added call to update items name with uuid
=> [_]: Added update name of items with uuid

package.json, src/drive/storage/index.ts, src/drive/storage/types.ts
- Added call to get the folder tree of a specific folder from uuid
=> [_]: feature/Added getFolderTree call

package.json, src/drive/payments/index.ts
Now, we return a parameter only when the invoice status indicates that it has already been paid.
=> [_]: feat/new parameter indicating the invoice status

package.json, src/drive/storage/index.ts, src/drive/storage/types.ts
- Added calls to check duplicated file and folder names
=> [PB-2375]: Check duplicated items before uploading on Drive web

src/drive/users/index.ts, src/drive/users/types.ts, test/drive/users/index.test.ts
Details:
- We need to migrate server wip endpoint , so this endpoint is named 'users' 
- Also in /users/password the encryptVersion field is required in payload from backend server-wip 
Updates:
- Changed old endpoint `changePassword` as `changePasswordLegacy`
- Added new `changePassword` call to new endpoint
- Added `encryptVersion` in payload
=> [_]: feat change user path to users in changePassword

package.json, src/drive/storage/index.ts
- Add `isSharedItem` in the request to non-block the details of the files/folders.
- wip: https://github.com/internxt/drive-server-wip/pull/399
- web : https://github.com/internxt/drive-web/pull/1290
=> [PB-2424] Feat: allow folder ancestors shared

package.json, src/drive/storage/index.ts, test/drive/storage/index.test.ts
- Migrating the Recents endpoint to the new API.
=> [PB-2979]: feat/migrate recents endpoint to the new API

package.json, src/workspaces/index.test.ts, src/workspaces/index.ts, src/workspaces/types.ts
- Mark the spaceLimit parameter as optional when inviting a user.
- Allow the owner to modify the storage of an existent member.
- Get the workspace usage info (totalWorkspaceSpace, spaceAssigned, spaceUsed).
=> [PB-2345]: fix/mark space limit as optional when inviting a member to workspace and modify the existent member usage 

.eslintrc.json, package.json, src/drive/storage/index.ts
Searching for items in B2B doesn't return any result, instead it shows the items in B2C. When clicking on a result, the app crashes.
=> [PB-2981]: feat/[B2B – Drive] - fuzzy search for b2b items

package.json, src/auth/index.ts
Add salt to upgradeHash request
P.S. Argon2 outputs results like this, where salt is already included into the hash `$argon2id$v=19$m=65536,t=2,p=1$gZiV/M1gPc22ElAH/Jh1Hw$CWOrkoo7oJBQ/iyh7uJ0LO2aLEfrHwTWllSAxT0zRno`. However, to keep the same workflow, the salt will be sent to the database along with the hash
=> [PB-3078] add salt to the upgrade request

.github/workflows/ci.yml, .github/workflows/code-coverage.yml, .github/workflows/publish.yml, package.json, src/auth/index.ts, src/auth/types.ts, src/drive/share/types.ts, src/drive/users/types.ts, src/shared/types/userSettings.ts, src/workspaces/index.test.ts, src/workspaces/index.ts, src/workspaces/types.ts, test/auth/index.test.ts, test/auth/registerDetails.mother.ts, yarn.lock
Remove all changes done for kyber and argon2
=> Rollback all kyber and argon2 changes

package.json, src/drive/payments/index.ts, src/drive/payments/types.ts
Fetch the invoices depending on the userType (`individual` or `business`) to get all invoices the user has, not only for the current subscriptionId if there is any. 
With this change, we can also fetch the lifetime invoices for `UserType.Individual` type.
=> [PB-3585]: fix/get invoices for each plan type

package.json, src/shared/types/userSettings.ts
Keys in UserSettings are unencrypted, the name should reflect it
=> fix names in UserSettings and up the version

package.json, src/auth/index.ts, src/drive/users/index.ts, src/drive/users/types.ts
Update migrated endpoints:
- GET /api/are-credentials-correct
- POST /api/user/sendVerificationEmail
- POST /api/user/verifyEmail
=> migrate are-credentials-correct sendVerificationEmail and verifyEmail

package.json, src/drive/payments/index.ts, src/drive/payments/types.ts, test/drive/payments/index.test.ts
Currently, this new endpoint checks if the user can be able to use the Antivirus.
=> [PB-3724]: feat/check if user is elegible for new features

package.json, src/auth/index.ts, src/drive/users/index.ts
Add new API endpoints:
- PUT /api/users/avatar
- DELETE /api/users/avatar 
- PATCH /api/users/profile
- POST /api/users/deactivation/send
- POST /api/users/deactivation/confirm
=> [PB-3796]:Chore/Update user endpoints

package.json, src/drive/payments/types.ts
This PR introduces a new feature in the Internxt SDK that allows retrieving the lifetime product ID associated with a user.
In addition, we also obtain if the user can use backups depending on the plan the user has.
=> [_]: feat/get lifetime product id

package.json, src/auth/index.ts, src/auth/types.ts, test/auth/index.test.ts
Add support for optionally updating private keys during account recovery. 
server-wip changes: #internxt/drive-server-wip/pull/506
=> [PB-3702]: feat/recover account with keys

package.json, src/drive/index.ts, src/drive/payments/object-storage.ts, test/drive/payments/object-storage.test.ts
This PR implements the Object Storage endpoints to use them from the website so we can create the object storage subscription.
=> [PB-4199]: feat/object storage endpoints

src/network/index.ts, src/shared/headers/index.ts, test/network/network.test.ts
1. Added `x-internxt-desktop-header` header to `headersWithAuthToken` and `headersWithBasicAuth` using AppDetails object.
` const client = Network.client('url', {..., desktopHeader: 'token' }, ....)`
Note:
Branch off https://github.com/internxt/sdk/pull/280
=> [PB-4224]: feat/add additional desktop headers in network constructor

package.json, src/index.ts, src/payments/checkout.ts, src/payments/index.ts, src/payments/types/index.ts, src/shared/headers/index.ts, src/shared/types/apiConnection.ts
This PR implements new endpoints for the integrated checkout:
- Get customer Id
- Create subscription
- Create payment intent
- Get price by ID and its taxes
=> [PB-4357]: feat/checkout endpoints

package.json, src/drive/storage/index.ts, src/drive/storage/types.ts, test/drive/storage/index.test.ts
Added two new methods to call the limit and usage endpoints on drive-server-wip. 
Removed fileId on the new create thumbnail endpoint to coincide with the changes introduced in drive-server-wip
=> [PB-4369]: feat/new limits usage endpoints

package.json, src/drive/payments/object-storage.ts, test/drive/payments/object-storage.test.ts
This PR contains updates for the object storage endpoints:
- Added new parameters to object storage endpoints to enable calculation of additional taxes for upcoming user subscriptions.
- Updated the endpoint paths.
=> [PB-4388]: feat/update object storage functions

package.json, src/drive/backups/index.ts, src/drive/storage/types.ts, test/drive/backups/index.test.ts
It creates the new backups endpoints that use drive-new backend
=> [PB-4475]: feat/migrate-backups-endpoints

package.json, src/drive/payments/object-storage.ts, src/payments/types/index.ts, test/drive/payments/object-storage.test.ts
This PR allows the user to verify the payment method before creating an object storage subscription.
=> [PB-4396]: feat/payment method verification

package.json, src/drive/share/index.ts, src/drive/share/types.ts, test/drive/share/index.test.ts
This PR adds a new endpoint to retrieve the type of a shared item. It allows us to determine whether the shared item is of type `public` or `private`, so that we can inform the user accordingly in the UI.
=> [PB-3615]: feature/sharing info endpoint

package.json, src/drive/users/index.ts, src/shared/http/client.ts
This PR fixes an issue where the avatar image was not being correctly sent to the backend when updating the user's avatar. We now use Axios's `putForm` method to properly handle `FormData` and ensure the Blob is transmitted as expected. This change prevents missing payload issues.
=> [_]: fix/use Axios putForm to correctly upload avatar image

package.json, src/auth/index.ts
This PR adds support for custom HTTP headers in all authentication endpoints so clients can include a reCAPTCHA token via the `x-internxt-captcha` header.
=> [PB-4499]: feat/allow custom headers for auth endpoints

package.json, src/drive/users/index.ts, test/drive/users/index.test.ts
- Handled apiSecurity `undefined` case in Users constructor
=> [_]: bugfix/Hadle Users apiSecurity undefined
