- src/auth/index.ts
- src/auth/types.ts
- test/auth/index.test.ts
- test/shared/response.ts
Improved readability and error management
> [SDK-2] feature/login

- src/auth/index.ts
- src/auth/types.ts
- test/auth/index.test.ts
- test/drive/storage/mothers/updateFolderMetadataPayload.mother.ts
Add methods on Auth module to request the API about the TwoFactorAuthentication and the account deactivation.
> [SDK-33] feature/auth

- src/drive/index.ts
- src/drive/payments/index.ts
- src/drive/payments/types.ts
- test/drive/payments/index.test.ts
Adds two endpoints related to payments and product plans
> [SDK-17] feature/payments-module

- src/drive/share/index.ts
- src/drive/share/types.ts
- test/drive/share/index.test.ts
A new method to request has been added to request the necessary data to generate a new link to share a folder.
Some modifications have been done to the method to generate a link to share file so it matches the syntax.
> []: feature/share-folder

- package.json
- changes package.json version to 0.7.3
> [_]: feat/0.7.3

- src/network/index.ts
- test/network/network.test.ts
- Points download links endpoint to the getting file info endpoint
> [_]: feat/network-file-info

- src/network/download.ts
- src/network/types.ts
- test/network/download.test.ts
- test/network/network.test.ts
- Adds a network download function that contains all the steps to perform a download
> [_]: feat/network-download

- src/network/types.ts
- Removes a TypeScript absolute path import that is causing troubles on build.
> [_]: fix/ts-build-import

- src/network/upload.ts
- test/network/upload.test.ts
- Adds a network upload function that contains all the steps to perform an upload
> [_]: feat/network-upload

- package.json
- src/network/download.ts
- src/network/index.ts
- src/shared/headers/index.ts
- test/network/download.test.ts
- Allows injecting a token on the download as an auth header.
> [_]: feat/allow-token-network-download

- package.json
- src/network/index.ts
- Changes 500 to 100MB for min size of file for multipart upload
> hotfix(network): change 500 to 100MB

- package.json
- src/photos/photos/index.ts
- src/photos/types.ts
This PR provides API access to check if a photo exists given the photo hash, the photo name and the photo date as ISO string.
> [_]: Feature - Add checking for photos that already exists

- package.json
- src/photos/photos/index.ts
I fucked up the response object, it was `res.data.photos` instead of `res.data`
> [_]: Fix photos exists return

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
- test/drive/share/index.test.ts
- Added code to generate share links
> Update share links with code

- src/drive/share/types.ts
added fileSize to ShareLink list type
> [_]: feat/add fileSize to ShareLink

- package.json
- src/drive/share/index.ts
added increment shared link view
> [_]: Feature/add increment share view

- package.json
- src/drive/share/index.ts
- replaced incrementShareView id with token
> [_]: Feature/replace incrementShareView id with token

- package.json
- src/drive/referrals/types.ts
> [_]: feat/invite-two-friends-label

- package.json
- src/photos/photos/index.ts
Adds a method to work with the photos find or create photo endpoint
new Photos endpoint was created here: https://github.com/internxt/photos-server/pull/40
> [_]:(feature) Add new find or create photos endpoint

- src/auth/index.ts
- test/auth/index.test.ts
- Switches the route for register (`/register` -> `/users`)
> [_]: feat/use-new-path-for-register

- package.json
- src/photos/photos/index.ts
- src/photos/types.ts
Adds a getUsage method that returns the total usage for the token user based on the files in the Photos DB
> [_]:(feature) Add getUsage method for photos

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- test/drive/storage/mothers/folderContentResponse.mother.ts
- Added method to allow to upload thumbnails
> [WT-103]: Feature/upload thumbnail

- src/drive/payments/types.ts
This type is necessary for checkout session generation with coupon code.
> [_]:(feature) adding coupon code type

- package.json
Update sdk version to 1.4.9 -> 1.4.10
> [_]:(feat)Update package.json version

- package.json
- src/photos/types.ts
Added new types for Photos.
- duration
- itemType
> [MT-21]:(feature) Added types for saving videos duration and itemType

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
- src/shared/headers/index.ts
- Enables sending headers with password to retrieve a protected link
- Enables sending request with password to create a protected link
> [WT-65]: Feat/add password protected shared links

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- test/drive/storage/index.test.ts
- test/drive/storage/mothers/folderContentResponse.mother.ts
- Enables to add plain_name to files in database (folders plain_name is managed in drive-server)
> [WT-145] feature/add plain name to files and folders

- package.json
- src/drive/storage/types.ts
- Fixed drive storage types (plain_name cant be null and deleted is boolean)
> [_]: Fix/drive storage types

- src/photos/photos/index.ts
- src/photos/types.ts
Update a photo by ID, currently only previews update is allowed
> [_]:(feature) Update photo by ID method

- package.json
> [_]:(fix) set version to 1.4.18

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
- test/drive/share/index.test.ts
- Added shared folders parentId
> [WT-251]: Feat/Add shared folders parentId

- package.json
- src/drive/payments/types.ts
Update "DisplayPrices" interval. ('lifetime' plan added)
SDK version updated (patch changed from 19 -> 20)
> [_]: Feat/update payment types

- package.json
- src/photos/photos/index.ts
- src/photos/types.ts
- Add GET method to obtain the photos count
- Get the photos by updatedAt property instead of statusChangedAt
> [_]:(feature) Add photos count, improved get photos endpoint

- package.json
- src/photos/photos/index.ts
- Adds a new Photos method to retrieve the photos sorted by the given parameters.
- Adds the missing auth headers to the getPhotosCount method
- Bump version to 1.4.21
> [_]:(feature) Add getPhotosSorted method, add missing headers to getPhotosCount

- package.json
- src/drive/storage/index.ts
- src/shared/http/client.ts
- Added method to search items by name
> [WT-318]: Feat/Query to search files by substring

- package.json
- src/drive/storage/types.ts
- src/drive/trash/index.ts
- Added function to get paginated Trash items
> [_]: feature/Add function to get paginated trash items 

- package.json
- src/drive/payments/types.ts
The free trial parameter has been added to allow the user a free trial period.
> [_]: Fix/Add free trial param

- package.json
- src/photos/photos/index.ts
Add trash Photos methods to the Photos submodule
- Trash photo by ID allows to update a single Photo (maintained until we remove this from photos-server)
- Trash photos by ID allows to update multiple Photos at the same time
> [_]:(feature) Photos trash methods

- package.json
> Bump package version to 1.4.28

- package.json
- src/drive/referrals/index.ts
- src/drive/share/index.ts
- src/drive/storage/index.ts
- src/drive/trash/index.ts
- src/drive/users/index.ts
- src/shared/headers/index.ts
- src/shared/types/apiConnection.ts
- test/auth/index.test.ts
- test/drive/backups/index.test.ts
- test/drive/payments/index.test.ts
- test/drive/referrals/index.test.ts
- test/drive/share/index.test.ts
- test/drive/storage/index.test.ts
- test/drive/trash/index.test.ts
- test/drive/users/index.test.ts
- Removed unnecessary mnemonic params
> [_] : feature/Removed unnecessary mnemonic params

- package.json
- src/drive/payments/index.ts
- src/drive/payments/types.ts
added query to the payment api and check if the user has used the coupon
> [PB-20]feat:provide-incentive-during-cancellation

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- src/shared/http/client.ts
- test/drive/storage/mothers/folderContentResponse.mother.ts
- Added methods to get paginated items from drive
> [PB-256] - Integrate pagination in front end

- src/drive/payments/index.ts
- src/drive/payments/types.ts
Change the name of some functions to avoid confusion and the paths were also changed.
> [_]: fix/Change functions name and path names

- package.json
Update package version for new release.
> [_]: fix/Update package version

- package.json
- src/drive/storage/index.ts
Add query params sort and order to getFolderFiles and getFolderFolders
> [PB-440]: feat/add query param sort and order

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
Add endpoint to return the metadata of a specific file
> [PB-472]: feat/get file by uuid

- src/drive/payments/index.ts
- src/drive/payments/types.ts
Get the client secret from the setup intent to allow user to purchase a plan with his PayPal account.
> [MKT-125]: Feat/get the client_secret from the setup intent

- src/drive/share/index.ts
- src/drive/share/types.ts
- Added fetch of share domains
> [PB-119] feature/Rotate drive sharing file drive subdomain

- package.json
> [_]: Bump version

- package.json
- src/auth/index.ts
Added endpoints:
- Recover password via link
- Change password with backup key
> [PB-90]:  feat/Add recovery link and change password

- package.json
- src/auth/index.ts
Changes:
- Add reset account without backup key
> [PB-700]: feat/add reset account with token

- package.json
- src/drive/share/index.ts
- Changed the path to share a folder
> [_]: Changed share folder path

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
- Add get shared folder content
- Path changed of some enpoints
> [PB-550]: feat/add get shared folder content

- package.json
- src/drive/storage/index.ts
- src/shared/headers/index.ts
Changes:
- Added resourcesToken header param to File Upload, Thumbnail Upload and Rename file
> [PB-118]: Feat/add resources token

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
Changing the endpoints for the AFS function and changing some types to match the correct ones.
The ones that work correctly for now are:
* /invites
* /folders
> [_]: feat/update-shared-folder-endpoints

- package.json
- src/drive/payments/index.ts
Add coupon code to updateSubscriptionPrice to upgrade any payment plan to an offer.
> [PB-692]: feat/allow coupon code in updateSubscriptionPrice

- package.json
- src/drive/share/index.ts
Added optional token to decline and accept shared invitation calls
> [_]: Added optional token to decline and accept shared folder invitation calls

- package.json
- src/drive/share/types.ts
> [_]: Feature/change create public sharing endpoint

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- Add EP to allow global searches in drive
> [PB-250]: feat/add get global search items

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
Required to use: https://github.com/internxt/drive-server-wip/pull/218
> [PB-995]: feat/add sharing update and get sharing type endpoint

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- Added `getFolderAncestors` call
> [PB-1146]  feature/Add get folder ancestors endpoint to project and sdk

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- Added Get to obtain the meta of a folder with uuid
> [PB-472] add gets meta of given folder uuid

- package.json
- src/auth/index.ts
- src/auth/types.ts
- src/drive/share/index.ts
- src/drive/users/index.ts
- src/drive/users/types.ts
- test/auth/index.test.ts
- test/auth/registerDetails.mother.ts
- test/drive/share/index.test.ts
- test/drive/users/index.test.ts
Requirement for:
https://github.com/internxt/drive-web/pull/911
> feat: add pre create users and validate invitation

- package.json
- src/drive/users/index.ts
- src/drive/users/types.ts
- Added calls required for the email change process
> [PB-1425] feature/Add ability to update the email on Drive web

- package.json
- src/drive/users/types.ts
- Updated `VerifyEmailChangeResponse` types
> Updated verify email change call response types

- package.json
- src/auth/index.ts
- test/auth/index.test.ts
Enables auto account unblock endpoints.
Dependences:
https://github.com/internxt/drive-server-wip/pull/250
> [PB-22]: feat/add account unblock endpoints

- .gitignore
- package.json
- src/drive/users/index.ts
This PR adds the new return type for the change password request, including token and newToken
> [_]:(fix) Change password return type

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
- test/drive/share/index.test.ts
> [PB-701] feat/display folder size on shared landing page

- package.json
- src/drive/storage/types.ts
- test/drive/storage/mothers/folderContentResponse.mother.ts
Add uuid property to Drive file type
> [_]:(fix) Add file uuid property

- package.json
> [_]:Bump version to 1.4.73

- package.json
- src/drive/payments/index.ts
A new payments endpoint has been added to check if the user has used a coupon to purchase a plan.
> [_]: feat/add payment endpoint

- package.json
- src/index.ts
- src/workspaces/index.test.ts
- src/workspaces/index.ts
- src/workspaces/types.ts
- test/drive/storage/index.test.ts
> [PB-2064] feature/Added workspaces calls

- package.json
- src/drive/storage/types.ts
- test/drive/storage/index.test.ts
Add missing UUID property to create folder response
> [_]:(fix) Add missing UUID property to create folder response

- package.json
- src/workspaces/index.test.ts
- src/workspaces/index.ts
- src/workspaces/types.ts
- Added calls to accept and decline invitations to workspace
> [PB-2082] feature/Added accept and decline invitation to workspace calls

- package.json
- src/drive/storage/index.ts
- Added check file size limit call
> [PB-1442]: feature/Update web frontend (file size limit, items shared)

- package.json
- src/shared/http/client.ts
- src/shared/types/errors.ts
- Added code field to normalize error middleware
> Added code field to normalize error middleware

- package.json
- src/drive/users/index.ts
- Added call to obtain user data from drive-server-wip
> [PB-2251] feature/Obtain token when is expired

- package.json
- src/drive/storage/types.ts
- Modified CreateFolderResponse type
> [PB-2219]: feature/Modify CreateFolderResponse type

- package.json
- src/drive/storage/index.ts
- src/shared/headers/index.ts
- src/workspaces/index.test.ts
- src/workspaces/index.ts
- src/workspaces/types.ts
- Added create folder and file calls for workspaces
- Added get credentials of workspace call
- Added parameter to add custom headers to calls
> [PB-2183-PB-2203] feature/list-workspace-folder-and-files

- package.json
- src/drive/share/index.ts
- src/drive/share/types.ts
- src/drive/storage/index.ts
- src/drive/trash/index.ts
- src/shared/headers/index.ts
- src/shared/types/apiConnection.ts
- src/workspaces/index.test.ts
- src/workspaces/index.ts
- src/workspaces/types.ts
- Update sdk with missing workspace related endpoints
- Added workspaces token to ApiSecurity
> [PB-2242]: chore/update workspaces endpoints

- package.json
- src/drive/trash/index.ts
- src/drive/trash/types.ts
- Added Delete items by uuid endpoint and type
> [_]: Delete trash items payload type changed

- package.json
- src/workspaces/index.test.ts
- src/workspaces/index.ts
- src/workspaces/types.ts
- Added workpase usage endpoint
> [PB-2367] feature/Use correct member usage endpoint

- src/drive/payments/index.ts
- src/drive/payments/types.ts
- src/workspaces/index.test.ts
- src/workspaces/types.ts
- Add `phoneNumber` in workspaces 
- Add new endpoint to update the customer billings details
- https://github.com/internxt/drive-web/pull/1192
> Feat: Customer billing details

- package.json
> [_]: Bump package version

- package.json
- src/drive/payments/types.ts
- Create/Modify interfaces to receive billing details
- https://github.com/internxt/drive-web/pull/1199
> Chore: updating payments types

- package.json
- src/drive/storage/index.ts
- src/workspaces/index.ts
- A resource token header has been added to some endpoints to work on shared folders
> [PB-2398] bugfix/Added resources token header for make work endpoint in shared folders

- package.json
- src/shared/types/userSettings.ts
- Added `rootFolderUuid` field in `UserSettings` interface
> [BR-249]: bugfix/Add rootFolderUuid field in user interface

- package.json
- src/drive/payments/index.ts
- src/drive/payments/types.ts
Creating or fetching the customer id to create the subscription or one time payment (lifetime plans).
> [MKT-412]: feat/integrated checkout

- package.json
- src/drive/payments/index.ts
Fetching and sending the customer token to integrated checkout endpoints.
> [_]: feat/fetching and sending token

- package.json
- src/workspaces/index.test.ts
- src/workspaces/index.ts
- src/workspaces/types.ts
- edited get team members endpoint
> [PB-2407] feature/edit get team members endpoint

- package.json
- src/drive/payments/index.ts
Allowing multi currency for integrated checkout.
> [_]: feat/allow multi currency

- package.json
- src/workspaces/index.test.ts
- src/workspaces/index.ts
- src/workspaces/types.ts
Update deleteTeam and changeTeamManager
> [PB-2371] edit team endpoints

- package.json
- src/drive/payments/index.ts
- src/workspaces/index.test.ts
- Added `userType` to update subscription call
> [PB-2437]: feature/Add possibility to update b2b subscription plan

- package.json
- src/drive/payments/index.ts
- Added payment `id` to return types of `createPaymentIntent` call
> [_]: feature/Add id to return types of createPaymentIntent

- package.json
- src/workspaces/index.ts
- Delete or remove user from a workspace
- https://github.com/internxt/drive-web/pull/1236
> [PB-2392] Feat: remove user from workspace

- package.json
- src/drive/storage/types.ts
> [PB-2612] fix/backups items name

- package.json
- src/drive/payments/index.ts
Update endpoints to create customer and subscription to obtain all the necessary data to create a subscription for business.
> [MKT-427]: feat/create customer and create subscription for b2b plans

- package.json
- src/drive/storage/index.ts
Adding optional parameters to getFolderContentByUuid to get the items paginated.
> [PB-2376]: feat/add pagination to getFoldercontentByUuid endpoint

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- Add modification date when creating file
> [PB-2904] fix/keep modification date

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
> Revert "[PB-2904] fix/keep modification date"

- package.json
- src/drive/trash/index.ts
- Add endpoint to get sorted trash items
> [PB-2901] feat/add sort items to trash view

- package.json
- src/workspaces/index.ts
- src/workspaces/types.ts
- Add new endpoints to list workspace shared folders and files
> [PB-2301] feat/sharing content between teams

- package.json
- src/drive/storage/index.ts
- src/drive/storage/types.ts
- Adds getFolderByPath functionality
- Adds getFileByPath functionality
- Adds updateFileMetaByUUID functionality (file and type renaming)
> [PB-1780]: feat/add update file meta and find items by path

- .gitignore
- .vscode/settings.json
- package.json
- src/auth/index.ts
- src/auth/types.ts
- src/drive/share/types.ts
- src/drive/users/types.ts
- src/shared/types/userSettings.ts
- src/workspaces/index.test.ts
- src/workspaces/types.ts
- test/auth/index.test.ts
- test/auth/registerDetails.mother.ts
- yarn.lock
Changes in structures required for drive-web migration to PQ and argon2
> [PB-2666]: Add pq keys and argon2

- package.json
- src/drive/storage/types.ts
- test/drive/storage/index.test.ts
- test/tsconfig.json
- tsconfig.json
- Fixed CreateFolderResponse type to match the real backend response
Create Folder Server Response: [https://github.com/internxt/drive-server-wip/blob/master/src/modules/folder/folder.attributes.ts](https://github.com/internxt/drive-server-wip/blob/master/src/modules/folder/folder.attributes.ts)
> [_]: fix/create-folder-response

- package.json
- src/drive/payments/index.ts
Sending the `workspaceId` when updating the members.
> [_]: feat/send the workspaceId when updating members

- package.json
- src/auth/index.ts
- src/auth/types.ts
- test/auth/index.test.ts
- test/auth/registerDetails.mother.ts
Remove one nesting data structure of the crypto keys in login
> [_]: refactor/remove-one-depth-level-on-crypto-keys-data-structure-on-login

- package.json
- src/auth/index.ts
- src/auth/types.ts
- src/shared/types/userSettings.ts
- test/auth/index.test.ts
- test/auth/registerDetails.mother.ts
> [PB-2666]: Add kyber keys to the sdk

- package.json
- src/drive/payments/index.ts
- src/network/index.ts
- src/shared/headers/index.ts
- src/shared/types/apiConnection.ts
- test/drive/payments/index.test.ts
- test/network/network.test.ts
This PR adds an additional header for the payment SDK builder so that the desktop application can send an extra header.
> [PB-4223]: feat/additional header to the construct client payment SDK

- package.json
> [_] feature/Bump package version

- package.json
Reopned to correctly bump version
> fix: correct version

- package.json
- src/drive/storage/types.ts
- src/drive/users/index.ts
- test/drive/storage/index.test.ts
- test/drive/storage/mothers/folderContentResponse.mother.ts
- Updated FetchFolderContentResponse type and related tests
> [PB-4385] feature/Update FetchFolderContentResponse type

- package.json
- src/auth/index.ts
- test/auth/index.test.ts
Add call to `recover-account-v2`
> [_]: feat/add changePasswordWithLinkV2

- src/drive/users/index.ts
- test/drive/users/index.test.ts
This PR fixes the implementation for `/users/avatar/refresh` endpoint.
> [_]: fix/refresh avatar user endpoint

- package.json
- src/drive/payments/types/tiers.ts
Added the property Cleaner inside Tier featuresPerService
> chore: Update drive/payments/Tier type to add cleaner property on featuresPerService

- package.json
- src/meet/index.test.ts
- src/meet/types.ts
- Added `appId` field in meet joinCall and createCall responses
> [PB-4278] featur/Add appId filed in join and createCall responses

- package.json
- src/drive/storage/types.ts
- src/drive/users/index.ts
- test/drive/storage/index.test.ts
- test/drive/storage/mothers/fileData.mother.ts
- Updates types to swagger schema
> [_]: feat/update-file-types

- package.json
- src/drive/payments/types/tiers.ts
This PR updates the Tier object that returns the Payments API.
> [PB-4998]: feat/update Tier object
